def add(*args, **kwargs): ...

def subtract(*args, **kwargs): ...

def multiply(*args, **kwargs): ...

def true_divide(*args, **kwargs): ...

def floor_divide(*args, **kwargs): ...

def divide(*args, **kwargs): ...

def logical_and(*args, **kwargs): ...

def logical_or(*args, **kwargs): ...

def where(*args, **kwargs): ...

def less(*args, **kwargs): ...

def less_equal(*args, **kwargs): ...

def greater(*args, **kwargs): ...

def greater_equal(*args, **kwargs): ...

def equal(*args, **kwargs): ...

def not_equal(*args, **kwargs): ...

def maximum(*args, **kwargs): ...

def minimum(*args, **kwargs): ...

