def sum(*args, **kwargs): ...

def mean(*args, **kwargs): ...

def var(*args, **kwargs): ...

def std(*args, **kwargs): ...

def prod(*args, **kwargs): ...

def count_nonzero(*args, **kwargs): ...

def any(*args, **kwargs): ...

def all(*args, **kwargs): ...

def max(*args, **kwargs): ...

def min(*args, **kwargs): ...

def logsumexp(*args, **kwargs): ...

