name: Test with pytest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PIP_ROOT_USER_ACTION: ignore
  PYTHONNOUSERSITE: "1"

permissions:
  contents: read
# pytest --setup-show -vv
jobs:
  test_py313:
    runs-on: ubuntu-latest
    steps:
    - name: Set up python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: "3.13"
    - uses: actions/checkout@v5
    - name: Install python dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install --no-cache-dir --upgrade pytest mlx[cpu] jax[cpu] tensorflow dask tinygrad array-api-compat eindex einops scipy flax
        python -m pip install torch --no-cache-dir --index-url https://download.pytorch.org/whl/cpu
        python -m pip install .
    - name: Run tests
      run: |
        source .venv/bin/activate

        python -m pytest test --disable-mlx-compile-values
        python -m pytest test/test_invalid_backend.py --noconftest



  # https://github.com/pytorch/pytorch/blob/main/RELEASE.md#release-compatibility-matrix

  test_py310_torch_xx_to_25:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        torch: ["2.5", "2.4", "2.3", "2.2", "2.1", "2.0", "1.13"]
    steps:
    - name: Set up python 3.10
      uses: actions/setup-python@v6
      with:
        python-version: "3.10"
    - uses: actions/checkout@v5
    - name: Install python dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install --no-cache-dir --upgrade pytest
        python -m pip install .

    - name: Run tests
      run: |
        source .venv/bin/activate

        if [[ "${{ matrix.torch }}" == "2.2" || "${{ matrix.torch }}" == "2.1" || "${{ matrix.torch }}" == "2.0" || "${{ matrix.torch }}" == "1.13" ]]; then
          python -m pip install --upgrade "numpy<2"
        fi

        python -m pip install --upgrade "torch==${{ matrix.torch }}" --no-cache-dir --index-url https://download.pytorch.org/whl/cpu

        if [[ "${{ matrix.torch }}" == "2.1" || "${{ matrix.torch }}" == "2.0" || "${{ matrix.torch }}" == "1.13" ]]; then
          python -m pytest test/test_invalid_backend_version.py
        else
          python -m pytest test
        fi

  test_py312_torch_26_to_212:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        torch: ["2.12", "2.11", "2.10", "2.9", "2.8", "2.7", "2.6"]
    steps:
    - name: Set up python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"
    - uses: actions/checkout@v5
    - name: Install python dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install --no-cache-dir --upgrade pytest
        python -m pip install .

    - name: Run tests
      run: |
        source .venv/bin/activate

        python -m pip install --upgrade "torch==${{ matrix.torch }}" --no-cache-dir --index-url https://download.pytorch.org/whl/cpu
        python -m pytest test
