name: Test with pytest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PIP_ROOT_USER_ACTION: ignore

permissions:
  contents: read
# pytest --setup-show -vv
jobs:
  test_py313:
    runs-on: ubuntu-latest
    steps:
    - name: Set up python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: "3.13"
    - uses: actions/checkout@v5
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pytest mlx[cpu] jax[cpu] torch tensorflow dask tinygrad array-api-compat eindex einops scipy flax
    - name: Run tests
      run: |
        pip install .
        pytest test --disable-mlx-compile-values
        pytest test/test_invalid_backend.py --noconftest



  # https://github.com/pytorch/pytorch/blob/main/RELEASE.md#release-compatibility-matrix

  test_py310_torch_xx_to_25:
    runs-on: ubuntu-latest
    steps:
    - name: Set up python 3.10
      uses: actions/setup-python@v6
      with:
        python-version: "3.10"
    - uses: actions/checkout@v5
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pytest

    - name: Run tests
      run: |
        pip install .

        pip install --upgrade "torch==2.5"
        pytest test
        pip install --upgrade "torch==2.4"
        pytest test
        pip install --upgrade "torch==2.3"
        pytest test
        pip install --upgrade "torch==2.2" "numpy<2"
        pytest test
        pip install --upgrade "torch==2.1" "numpy<2"
        pytest test/test_invalid_backend_version.py
        pip install --upgrade "torch==2.0" "numpy<2"
        pytest test/test_invalid_backend_version.py
        pip install --upgrade "torch<2" "numpy<2"
        pytest test/test_invalid_backend_version.py

  test_py312_torch_26_to_210:
    runs-on: ubuntu-latest
    steps:
    - name: Set up python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"
    - uses: actions/checkout@v5
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pytest

    - name: Run tests
      run: |
        pip install .

        pip install --upgrade "torch==2.10"
        pytest test
        pip install --upgrade "torch==2.9"
        pytest test
        pip install --upgrade "torch==2.8"
        pytest test
        pip install --upgrade "torch==2.7"
        pytest test
        pip install --upgrade "torch==2.6"
        pytest test
